import Foundation
import Testing
@testable import OmakeyProtocol

/// Reproduces docs/test-vectors.json from the daemon repo (generated by
/// `omakeyd test-vectors`) byte for byte. Refresh the copy in Fixtures with
/// scripts/sync-vectors.sh whenever the daemon regenerates it.
struct TestVectorsTests {
    let v: [String: Any]

    init() throws {
        let url = try #require(Bundle.module.url(forResource: "test-vectors", withExtension: "json", subdirectory: "Fixtures"))
        v = try #require(JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any])
    }

    private func obj(_ name: String) -> [String: Any] { v[name] as! [String: Any] }
    private func hex(_ name: String, _ o: [String: Any]? = nil) -> [UInt8] { Hex.decode((o ?? v)[name] as! String)! }
    private func int(_ name: String, _ o: [String: Any]) -> Int { (o[name] as! NSNumber).intValue }

    /// Hands out the vector's random bytes in the order the client asks for them.
    final class FixedRandom: RandomBytes {
        private var queue: [[UInt8]]
        init(_ chunks: [UInt8]...) { queue = chunks }
        func bytes(_ count: Int) -> [UInt8] {
            let next = queue.removeFirst()
            precondition(next.count == count, "asked for \(count) bytes, vector has \(next.count)")
            return next
        }
    }

    private func client(_ keys: KeyState) throws -> ClientSession {
        let host = try PairingURI.parse(v["pair_uri"] as! String)
        let hello = obj("hello")
        return ClientSession(
            host: host, phoneName: hello["name"] as! String, keys: keys,
            platform: Wire.platformAndroid, // as the vectors were made
            random: FixedRandom(hex("client_random"), hex("nonce", hello))
        )
    }

    @Test func pairURIMatches() throws {
        let h = try PairingURI.parse(v["pair_uri"] as! String)
        #expect(h.hostId == v["host_id"] as! String)
        #expect(h.name == "omarchy desk")
        #expect(h.deviceId == hex("device_id"))
        #expect(h.key == hex("device_key"))
        #expect(h.addresses == ["192.168.50.219", "100.67.193.30"])
        #expect(h.port == 47800)
        #expect(h.fingerprint == "630D-CD29")
    }

    @Test func sessionKeysMatch() {
        let k = SessionKeys.derive(deviceKey: hex("device_key"), clientRandom: hex("client_random"), serverRandom: hex("server_random"))
        #expect(Hex.encode(k.clientToServer) == v["kcs"] as! String)
        #expect(Hex.encode(k.serverToClient) == v["ksc"] as! String)
    }

    @Test func wholeSessionMatchesByteForByte() throws {
        let keys = KeyState()
        let client = try client(keys)

        #expect(Hex.encode(client.helloPacket()) == obj("hello")["packet"] as! String)

        let welcomeV = obj("welcome")
        let result = client.receive(hex("packet", welcomeV), nowMs: 0)
        guard case let .connected(hostName, sessionId, features, _) = result else {
            Issue.record("no WELCOME: \(String(describing: result))")
            return
        }
        #expect(hostName == welcomeV["host_name"] as! String)
        #expect(Int(sessionId) == (v["session_id"] as! NSNumber).intValue)
        // The server advertises the touchpad.
        #expect(features == int("features", welcomeV))
        #expect(features & Wire.featurePointer == Wire.featurePointer)

        let in1 = obj("input1")
        #expect(keys.press(125))
        #expect(Hex.encode(client.inputPacket(clientTimeMs: UInt32(int("client_time_ms", in1)))!) == in1["packet"] as! String)

        let in2 = obj("input2")
        #expect(keys.press(57))
        #expect(Hex.encode(client.inputPacket(clientTimeMs: UInt32(int("client_time_ms", in2)))!) == in2["packet"] as! String)

        // Left button down (sent on its own, counter 3), then motion and scroll ride the next INPUT.
        let in4 = obj("input4")
        #expect(keys.press(Wire.btnLeft))
        _ = client.inputPacket(clientTimeMs: 1032)
        let p = in4["pointer"] as! [String: Any]
        keys.addMotion(dx: Float(int("dx", p)), dy: Float(int("dy", p)))
        keys.addScroll(v: Float(int("wheel", p)), h: Float(int("hwheel", p)))
        #expect(Hex.encode(client.inputPacket(clientTimeMs: UInt32(int("client_time_ms", in4)))!) == in4["packet"] as! String)

        let ackV = obj("ack")
        let now = UInt32(int("client_time_ms", ackV) + 5)
        #expect(client.receive(hex("packet", ackV), nowMs: now) == .acked(pingMs: 5, leds: nil, theme: nil))
        #expect(keys.hasUnacked) // event 3, the button press, is newer than this ACK

        #expect(Hex.encode(client.byePacket()!) == obj("bye")["packet"] as! String)
    }

    @Test func clipPutAndReplyMatchByteForByte() throws {
        let client = try client(KeyState())
        _ = client.helloPacket()
        let result = client.receive(hex("packet", obj("welcome")), nowMs: 0)
        guard case let .connected(_, _, features, _) = result else {
            Issue.record("no WELCOME")
            return
        }
        // The vectors' WELCOME offers the touchpad only; the packets are the same either way.
        #expect(features & Wire.featureClipboard == 0)

        let put = obj("clip_put")
        let t = try #require(ClipTransfer.put(put["text"] as! String, paste: true, sensitive: false, id: UInt32(int("clip_id", put))))
        client.clip = t
        #expect(Hex.encode(client.clipPacket(nowMs: 0)!) == put["packet"] as! String)
        // Not due again until the resend time.
        #expect(client.clipPacket(nowMs: 10) == nil)

        #expect(client.receive(hex("packet", obj("clip_reply")), nowMs: 20) == .clipDone(.sent))
        #expect(client.clip == nil)
    }

    @Test func iosHelloSaysIOS() throws {
        let host = try PairingURI.parse(v["pair_uri"] as! String)
        let client = ClientSession(host: host, phoneName: "iPhone", keys: KeyState())
        let p = try #require(Packet.parse(client.helloPacket()))
        let plain = try #require(p.open(Aead(key: host.key)))
        let hello = try #require(Hello.decode(plain))
        #expect(hello.platform == Wire.platformIOS)
        #expect(hello.name == "iPhone")
    }
}
